// ============================================================
// FILE: src/pipeline/domain/domains.ts
// PURPOSE: Domain keyword dictionaries
// ============================================================

import type { DomainCategory } from '../../shared/types.js';

export interface DomainKeywords {
  routes: string[];
  components: string[];
  texts: string[];
  dependencies: string[];
  filenames: string[];
}

export const DOMAIN_KEYWORDS: Record<DomainCategory, DomainKeywords> = {
  ecommerce: {
    routes: [
      'cart',
      'checkout',
      'product',
      'products',
      'shop',
      'catalog',
      'order',
      'orders',
      'wishlist',
      'payment',
      'shipping',
    ],
    components: [
      'productcard',
      'cartitem',
      'pricedisplay',
      'addtocart',
      'checkoutform',
      'shoppingcart',
      'productlist',
      'productgrid',
      'orderconfirmation',
      'paymentform',
    ],
    texts: [
      'add to cart',
      'buy now',
      'free shipping',
      'in stock',
      'out of stock',
      'price',
      'quantity',
      'checkout',
      'place order',
      'shopping cart',
      'wishlist',
      'subtotal',
      'total',
    ],
    dependencies: [
      'stripe',
      '@stripe/stripe-js',
      '@stripe/react-stripe-js',
      'shopify',
      '@saleor',
      'medusa',
      'snipcart',
      '@paypal',
      'commerce.js',
      '@moltin',
    ],
    filenames: ['cart', 'checkout', 'product', 'shop', 'catalog', 'order', 'payment', 'shipping'],
  },
  saas: {
    routes: [
      'dashboard',
      'settings',
      'billing',
      'team',
      'workspace',
      'analytics',
      'onboarding',
      'integrations',
      'api-keys',
      'usage',
      'plan',
      'subscription',
      'admin',
      'invite',
    ],
    components: [
      'sidebar',
      'dashboard',
      'plancard',
      'usagechart',
      'teammember',
      'invitemodal',
      'settingspanel',
      'analyticswidget',
      'onboardingwizard',
      'billingform',
    ],
    texts: [
      'upgrade',
      'free trial',
      'workspace',
      'team members',
      'usage',
      'plan',
      'subscribe',
      'billing',
      'api key',
      'integration',
      'dashboard',
      'analytics',
      'onboarding',
      'invite',
    ],
    dependencies: [
      '@auth0/auth0-react',
      'next-auth',
      '@clerk/nextjs',
      'clerk',
      'supabase',
      '@supabase/supabase-js',
      'firebase',
      '@stripe/stripe-js',
      'intercom',
      'crisp',
      'posthog',
    ],
    filenames: [
      'dashboard',
      'settings',
      'billing',
      'team',
      'workspace',
      'analytics',
      'onboarding',
      'admin',
    ],
  },
  content: {
    routes: [
      'blog',
      'article',
      'articles',
      'post',
      'posts',
      'feed',
      'explore',
      'discover',
      'category',
      'categories',
      'tag',
      'tags',
      'archive',
      'search',
      'author',
    ],
    components: [
      'articlecard',
      'postcard',
      'blogpost',
      'feeditem',
      'commentlist',
      'commentform',
      'taglist',
      'categorylist',
      'richtext',
      'markdown',
      'contenteditor',
    ],
    texts: [
      'read more',
      'published',
      'author',
      'comments',
      'share',
      'related articles',
      'tags',
      'category',
      'subscribe',
      'newsletter',
      'bookmark',
      'reading time',
    ],
    dependencies: [
      '@sanity/client',
      'contentful',
      'strapi',
      'ghost',
      'prismic',
      'mdx-bundler',
      'next-mdx-remote',
      '@headlessui/react',
      'react-markdown',
      'remark',
    ],
    filenames: ['blog', 'article', 'post', 'feed', 'content', 'editor', 'comment', 'author'],
  },
  devtool: {
    routes: [
      'docs',
      'documentation',
      'api',
      'playground',
      'console',
      'terminal',
      'logs',
      'debug',
      'cli',
      'sdk',
      'reference',
      'sandbox',
    ],
    components: [
      'codeblock',
      'terminal',
      'console',
      'playground',
      'apiexplorer',
      'docsidebar',
      'codemirror',
      'monaco',
      'syntaxhighlighter',
      'cli',
      'logviewer',
    ],
    texts: [
      'api reference',
      'documentation',
      'cli',
      'sdk',
      'endpoint',
      'request',
      'response',
      'playground',
      'terminal',
      'console',
      'run',
      'execute',
      'deploy',
    ],
    dependencies: [
      '@codemirror/state',
      '@codemirror/view',
      'monaco-editor',
      '@monaco-editor/react',
      'prismjs',
      'shiki',
      'xterm',
      '@xterm/xterm',
      'nextra',
      'docusaurus',
    ],
    filenames: ['docs', 'api', 'playground', 'console', 'terminal', 'cli', 'sdk', 'sandbox'],
  },
  healthcare: {
    routes: [
      'patient',
      'patients',
      'appointment',
      'appointments',
      'medical',
      'health',
      'records',
      'prescription',
      'doctor',
      'doctors',
      'vitals',
      'lab',
      'diagnosis',
    ],
    components: [
      'patientcard',
      'appointmentform',
      'vitalschart',
      'prescriptionlist',
      'medicalrecord',
      'doctorprofile',
      'healthdashboard',
      'labresults',
      'diagnosisform',
    ],
    texts: [
      'patient',
      'appointment',
      'prescription',
      'diagnosis',
      'medical record',
      'vitals',
      'blood pressure',
      'heart rate',
      'doctor',
      'schedule appointment',
      'lab results',
      'health',
    ],
    dependencies: [
      'fhir',
      '@smile-cdr/fhir',
      'hl7',
      'dicom',
      '@medplum/core',
      'healthcare',
      'epic-fhir',
    ],
    filenames: [
      'patient',
      'appointment',
      'prescription',
      'medical',
      'health',
      'vitals',
      'doctor',
      'diagnosis',
    ],
  },
  general: {
    routes: [],
    components: [],
    texts: [],
    dependencies: [],
    filenames: [],
  },
};
